---
title: '2019-04-24'
output: html_document
---

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],tz="America/New_York") -> nyDateTime
invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tzone="UTC")

ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],tz="America/New_York") -> tpDateTime
invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tzone="UTC")

invoiceList
```


```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")


gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```


請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
library(lubridate)
fromDateTime <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
toDateTime <- with_tz(fromDateTime,tzone="Asia/Taipei")
toDateTime
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  fromDateTime <- ymd_hms(input,tz=fromTzone)
  toDateTime <- with_tz(fromDateTime,tzone=toTzone)
  return(toDateTime)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```


```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```

```{r}
twDates
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911 #+代表數字們
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd
```

請寫一個函數其名稱為date_convert_twYM，且date_convert_twYM(x)可以把一個民國年月字串物件x轉成date time class的西元年月日物件輸出。
```{r}
library(stringr); library(lubridate)
date_convert_twYM <- function(x){
  yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911 #+代表數字們
mm<-str_extract(x,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
date_convert_twYM(twDates)
```


##預設
```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```

將日期變為可更改，但有預設值
```{r}
library(stringr); library(lubridate)
date_convert_twYM <- function(x,dd="01"){
  yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911 #+代表數字們
mm<-str_extract(x,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  return(yyyymmdd)
}
date_convert_twYM(twDates,"03")
```

