---
title: '2019-04-24'
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Mat1
names(Mat1) 
```

```{r}
names(Mat1) <- letters[1:6]
names(Mat1)
```

```{r}
StuDF
colnames(StuDF) <- c("StudentID","Name","Grade")
rownames(matObj1)
StuDF
```



```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b
b$元素3 <- FALSE #可用[[]]or$($為list物件獨有的取法)
b[[5]] <- "7"
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```


```{r}
exData3$期間 -> temp
library(lubridate)
temp <- ymd(temp)
exData3$期間 <- temp
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- ymd("1997-06-01") <= exData3$期間 & exData3$期間 <= ymd("1998-12-01")
exData3$isAsiaCrisis
```

```{r}
exData3[exData3$isAsiaCrisis == T,]
exData3[exData3$isAsiaCrisis,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee",]
```


```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```

```{r}
test1 <- function(x,alpha){
  test1value <- x + alpha
  return(test1value)
}
test1(3,2)
```

```{r}
supply_fun <- function(a,b,P){
  Qs <- a + b * P 
  return(Qs)
}

demand_fun <- function(c,d,P){
  Qd <- c - d * P
  return(Qd)
}
```

```{r}
supply_fun(0,1,1)
demand_fun(5,1,P=1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  sum(transcriptDataFinal$學期成績[logiChosenStudent]*
    transcriptDataFinal$學分數[logiChosenStudent])/
    sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun("92aS67fee")
```

```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```

