---
title: '2019-06-12'
author: "林茂廷"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

#body
```{r}
i <- 1
print(studentIds5[[i]])
```
#for loop
```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

#範例二
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
library(stringr)
for(i in seq_along(gmailAddress)){
  if(str_detect(gmailAddress[[i]],"@gmail.com")){
    print(gmailAddress[[i]])
  }else{
    print(str_c(gmailAddress[[i]],"@gmail.com"))
  }
}
```

```{r}
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```


```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$author$name == commitHistory[[i]]$commit$committer$name)
}
```


```{r}
saveCharacter <- vector("character",5)
saveCharacter
```
```{r}
saveNumeric <- vector("numeric",5)
saveNumeric
```
```{r}
saveLogical <- vector("logical",5)
saveLogical
```
```{r}
saveList <- vector("list",5)
saveList
```

```{r}
# 把"你好"存在saveCharacter第3個位置
saveCharacter # 儲存前
saveCharacter[[3]] <- "你好"
saveCharacter # 儲存後
```

```{r}
# 把 72.3 存在saveNumeric第3個位置
saveNumeric # 儲存前
saveNumeric[[3]] <- 72.3
saveNumeric # 儲存後
```
# 把 TRUE 存在saveLogical第3個位置
```{r}
saveLogical # 儲存前
saveLogical[[3]] <- TRUE
saveLogical # 儲存後
```
# 把 list(姓名="小明",電話="02-86741111") 存在saveList第3個位置
```{r}
saveList # 儲存前
saveList[[3]] <- list(姓名="小明",電話="02-86741111")
saveList # 儲存後
```


```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```

#先創造一個空的vector
```{r}
saveGPA5 <- vector("numeric", length(studentIds5))
for(i in seq_along(studentIds5)){
  gpa_fun(studentIds5[[i]]) -> saveGPA5[[i]]
}
saveGPA5
```

```{r}
names(saveGPA5) <- studentIds5
saveGPA5
```

範例3 任務
0. saving container
```{r}
saveEveryThing <- vector("list",length(commitHistory))
saveSameLogi <- vector("logical",length(commitHistory))
```

1. sequence source
```{r}
commitHistory
```

2. body
```{r}
i <- 1

author_i <- commitHistory[[i]]$commit$author$name
committer_i <- commitHistory[[i]]$commit$committer$name
commitDate_i <- commitHistory[[i]]$commit$committer$date

(author_i==committer_i) -> saveSameLogi[[i]]
list(
  author=author_i,
  committer=committer_i,
  commitDate=commitDate_i
) -> saveEveryThing[[i]]
```
檢查一下
```{r}
saveEveryThing
saveSameLogi
```

3. for loop
```{r}
saveEveryThing <- vector("list",length(commitHistory))
saveSameLogi <- vector("logical",length(commitHistory))
for(i in seq_along(commitHistory)){
  author_i <- commitHistory[[i]]$commit$author$name
  committer_i <- commitHistory[[i]]$commit$committer$name
  commitDate_i <- commitHistory[[i]]$commit$committer$date

  (author_i == committer_i) -> saveSameLogi[[i]]

  list(
    author=author_i,
    committer=committer_i,
    commitDate=commitDate_i
  ) -> saveEveryThing[[i]]  
}
saveEveryThing
print(saveSameLogi)
saveEveryThing[saveSameLogi] -> saveValidCommitDate
saveValidCommitDate
```
