---
title: "Untitled"
output: html_document
---

```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
utility_cobb_douglass(1,.beta=0.8,2,0.5)
utility_cobb_douglass(1,.beta=0.8,.alpha=0.5,2)
```

# iteration
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
```

```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]
studentIds5
```

```{r}
for(i in studentIds5){
  print(i) #印出studentIds5[[i]]
}
```

```{r}
for(i in studentIds5){
  print(i)
  print(gpa_fun(i))
}
```

```{r}
for(i in c(1:5)){
  print(i)
  print(studentIds5[[i]])
}
```


```{r}
seq_along(studentIds5)
```

```{r}
for(i in seq_along(studentIds5)){
  print(i)
  print(studentIds5[[i]])
}
```

練習
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
library(stringr)
for(i in seq_along(gmailAddress)){
  if(str_detect(gmailAddress[[i]],"@gmail.com")){
    print(i)
    print(gmailAddress[[i]])
  }else{
    print(i)
    print(str_c(gmailAddress[[i]],"@gmail.com"))
    
  }
}
```

